name: medic_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^3.1.3
  bubble_bottom_bar: ^1.2.0
  carousel_slider: null
  cupertino_icons: ^1.0.0
  extended_image: ^1.1.2
  fit_kit: ^1.1.2
  flutter_socket_io: ^0.6.0
  fluttertoast: ^7.1.5
  geocoder: ^0.2.1
  geolocator: ^6.0.0+4
  google_fonts: ^1.1.0
  http: ^0.12.2
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  line_awesome_flutter: ^1.0.1
  lottie: ^0.2.1
  native_pdf_renderer: ^2.3.2
  numeric_keyboard: null
  percent_indicator: null
  permission_handler: ^3.0.0
  provider: ^4.3.2+2
  razorpay_flutter: ^1.2.2
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
  adaptive_icon_background: "#ffffff"

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/img/
